# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\oleksiy.borodenko\.vscode\extensions\algoritmika.algopython-20230320.193254.0\temp\c_project\Cal_bmi_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Cal_bmi_window(object):
    def setupUi(self, Cal_bmi_window):
        Cal_bmi_window.setObjectName("Cal_bmi_window")
        Cal_bmi_window.resize(341, 262)
        self.centralwidget = QtWidgets.QWidget(Cal_bmi_window)
        self.centralwidget.setObjectName("centralwidget")
        self.weight = QtWidgets.QLabel(self.centralwidget)
        self.weight.setGeometry(QtCore.QRect(61, 41, 119, 18))
        self.weight.setStyleSheet("font-size: 20px; color : brown")
        self.weight.setObjectName("weight")
        self.height = QtWidgets.QLabel(self.centralwidget)
        self.height.setGeometry(QtCore.QRect(61, 69, 122, 18))
        self.height.setStyleSheet("font-size: 20px; color : brown")
        self.height.setObjectName("height")
        self.button_find = QtWidgets.QPushButton(self.centralwidget)
        self.button_find.setGeometry(QtCore.QRect(61, 106, 261, 28))
        self.button_find.setObjectName("button_find")
        self.button_clearing = QtWidgets.QPushButton(self.centralwidget)
        self.button_clearing.setGeometry(QtCore.QRect(61, 146, 261, 28))
        self.button_clearing.setObjectName("button_clearing")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(60, 190, 84, 18))
        self.result.setStyleSheet("font-size : 20px; color : brown")
        self.result.setObjectName("result")
        self.wrt_weight = QtWidgets.QLineEdit(self.centralwidget)
        self.wrt_weight.setGeometry(QtCore.QRect(200, 40, 121, 22))
        self.wrt_weight.setObjectName("wrt_weight")
        self.wrt_height = QtWidgets.QLineEdit(self.centralwidget)
        self.wrt_height.setGeometry(QtCore.QRect(200, 69, 121, 22))
        self.wrt_height.setObjectName("wrt_height")
        self.button_meaning = QtWidgets.QPushButton(self.centralwidget)
        self.button_meaning.setGeometry(QtCore.QRect(60, 220, 261, 28))
        self.button_meaning.setObjectName("button_meaning")
        self.tool_name = QtWidgets.QLabel(self.centralwidget)
        self.tool_name.setGeometry(QtCore.QRect(70, 10, 197, 21))
        self.tool_name.setObjectName("tool_name")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 190, 55, 16))
        self.label.setText("")
        self.label.setObjectName("label")
        Cal_bmi_window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Cal_bmi_window)
        QtCore.QMetaObject.connectSlotsByName(Cal_bmi_window)

    def retranslateUi(self, Cal_bmi_window):
        _translate = QtCore.QCoreApplication.translate
        Cal_bmi_window.setWindowTitle(_translate("Cal_bmi_window", "MainWindow"))
        self.weight.setText(_translate("Cal_bmi_window", "<html><head/><body><p><span style=\" font-size:9pt;\">Body weight in kg:</span></p></body></html>"))
        self.height.setText(_translate("Cal_bmi_window", "<html><head/><body><p><span style=\" font-size:9pt;\">Body height in cm:</span></p></body></html>"))
        self.button_find.setText(_translate("Cal_bmi_window", "Find out your BMI"))
        self.button_clearing.setText(_translate("Cal_bmi_window", "Clear"))
        self.result.setText(_translate("Cal_bmi_window", "<html><head/><body><p><span style=\" font-size:9pt;\">Your BMI = </span></p></body></html>"))
        self.button_meaning.setText(_translate("Cal_bmi_window", "What does it mean"))
        self.tool_name.setText(_translate("Cal_bmi_window", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#6d0036;\">Calculation of BMI tool</span></p></body></html>"))
