from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(716, 390)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.list_files = QtWidgets.QListWidget(self.centralwidget)
        self.list_files.setGeometry(QtCore.QRect(67, 99, 181, 141))
        self.list_files.setObjectName("list_files")
        self.wrtiting = QtWidgets.QTextEdit(self.centralwidget)
        self.wrtiting.setGeometry(QtCore.QRect(267, 99, 431, 281))
        self.wrtiting.setObjectName("wrtiting")
        self.l_note_name = QtWidgets.QLabel(self.centralwidget)
        self.l_note_name.setGeometry(QtCore.QRect(78, 9, 81, 31))
        self.l_note_name.setObjectName("l_note_name")
        self.new_note = QtWidgets.QPushButton(self.centralwidget)
        self.new_note.setGeometry(QtCore.QRect(71, 241, 86, 28))
        self.new_note.setObjectName("new_note")
        self.del_note = QtWidgets.QPushButton(self.centralwidget)
        self.del_note.setGeometry(QtCore.QRect(164, 241, 86, 28))
        self.del_note.setObjectName("del_note")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(70, 80, 81, 21))
        self.name_label.setObjectName("name_label")
        self.save_b = QtWidgets.QPushButton(self.centralwidget)
        self.save_b.setGeometry(QtCore.QRect(71, 276, 181, 28))
        self.save_b.setObjectName("save_b")
        self.save_changes = QtWidgets.QPushButton(self.centralwidget)
        self.save_changes.setGeometry(QtCore.QRect(71, 311, 181, 28))
        self.save_changes.setObjectName("save_changes")
        self.wrtiting.raise_()
        self.list_files.raise_()
        self.l_note_name.raise_()
        self.new_note.raise_()
        self.del_note.raise_()
        self.name_label.raise_()
        self.del_note.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.l_note_name.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#740000;\">Notes🗒</span></p></body></html>"))
        self.new_note.setText(_translate("MainWindow", "New note"))
        self.del_note.setText(_translate("MainWindow", "Delete note"))
        self.name_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#6d0036;\">Notes list</span></p></body></html>"))
        self.save_b.setText(_translate("MainWindow", "Save note"))
        self.save_changes.setText(_translate("MainWindow", "Save changes"))
