from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(286, 273)
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(51, 11, 220, 21))
        self.name.setObjectName("name")
        self.eng = QtWidgets.QCheckBox(self.centralwidget)
        self.eng.setGeometry(QtCore.QRect(52, 78, 107, 20))
        self.eng.setStyleSheet("font-size : 10 ; color : darkred; font-weight: bold")
        self.eng.setObjectName("eng")
        self.symbols = QtWidgets.QCheckBox(self.centralwidget)
        self.symbols.setGeometry(QtCore.QRect(52, 132, 118, 20))
        self.symbols.setStyleSheet("font-size : 10 ; color : darkred; font-weight: bold")
        self.symbols.setObjectName("symbols")
        self.num = QtWidgets.QCheckBox(self.centralwidget)
        self.num.setGeometry(QtCore.QRect(52, 159, 82, 20))
        self.num.setStyleSheet("font-size : 10 ; color : darkred;  font-weight: bold")
        self.num.setObjectName("num")
        self.horizontalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.horizontalScrollBar.setGeometry(QtCore.QRect(60, 210, 160, 16))
        self.horizontalScrollBar.setStyleSheet("background-color: brown\n"
"")
        self.horizontalScrollBar.setMinimum(5)
        self.horizontalScrollBar.setMaximum(35)
        self.horizontalScrollBar.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalScrollBar.setObjectName("horizontalScrollBar")
        self.pasword_l = QtWidgets.QLabel(self.centralwidget)
        self.pasword_l.setGeometry(QtCore.QRect(60, 190, 99, 16))
        self.pasword_l.setObjectName("pasword_l")
        self.pas_length = QtWidgets.QLabel(self.centralwidget)
        self.pas_length.setGeometry(QtCore.QRect(160, 190, 55, 16))
        self.pas_length.setObjectName("pas_length")
        self.generate_b = QtWidgets.QPushButton(self.centralwidget)
        self.generate_b.setGeometry(QtCore.QRect(100, 240, 93, 28))
        self.generate_b.setStyleSheet("")
        self.generate_b.setObjectName("generate_b")
        self.ua = QtWidgets.QCheckBox(self.centralwidget)
        self.ua.setGeometry(QtCore.QRect(52, 105, 120, 20))
        self.ua.setStyleSheet("font-size : 10; color : darkred; font-weight: bold")
        self.ua.setObjectName("ua")
        self.show_result = QtWidgets.QLineEdit(self.centralwidget)
        self.show_result.setGeometry(QtCore.QRect(51, 48, 221, 22))
        self.show_result.setObjectName("show_result")
        self.name.raise_()
        self.pasword_l.raise_()
        self.ua.raise_()
        self.symbols.raise_()
        self.eng.raise_()
        self.num.raise_()
        self.horizontalScrollBar.raise_()
        self.pas_length.raise_()
        self.show_result.raise_()
        self.generate_b.raise_()
        SecondWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SecondWindow)
        self.horizontalScrollBar.valueChanged['int'].connect(self.pas_length.setNum) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "MainWindow"))
        self.name.setText(_translate("SecondWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#6d0036;\">Password generating tool</span></p></body></html>"))
        self.eng.setText(_translate("SecondWindow", "English letters"))
        self.symbols.setText(_translate("SecondWindow", "Special symbols"))
        self.num.setText(_translate("SecondWindow", "Numbers "))
        self.pasword_l.setText(_translate("SecondWindow", "<html><head/><body><p><span style=\" color:#7d0000;\">Password length:</span></p></body></html>"))
        self.pas_length.setText(_translate("SecondWindow", "<html><head/><body><p><span style=\" color:#7e0000;\">5</span></p></body></html>"))
        self.generate_b.setText(_translate("SecondWindow", "Generate"))
        self.ua.setText(_translate("SecondWindow", "Ukrainian letters"))
