from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(687, 412)
        font = QtGui.QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        MainWindow.setAnimated(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.b_notes = QtWidgets.QPushButton(self.centralwidget)
        self.b_notes.setGeometry(QtCore.QRect(81, 73, 129, 24))
        self.b_notes.setObjectName("b_notes")
        self.calendar = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar.setGeometry(QtCore.QRect(240, 10, 391, 241))
        self.calendar.setMinimumSize(QtCore.QSize(391, 151))
        self.calendar.setStyleSheet("background-color : darkred;\n"
"border : 1px solid black")
        self.calendar.setObjectName("calendar")
        self.l_tools = QtWidgets.QLabel(self.centralwidget)
        self.l_tools.setGeometry(QtCore.QRect(90, 10, 107, 21))
        self.l_tools.setObjectName("l_tools")
        self.list = QtWidgets.QListWidget(self.centralwidget)
        self.list.setGeometry(QtCore.QRect(80, 40, 131, 121))
        self.list.setObjectName("list")
        self.l_plans = QtWidgets.QLabel(self.centralwidget)
        self.l_plans.setGeometry(QtCore.QRect(80, 170, 145, 21))
        self.l_plans.setObjectName("l_plans")
        self.add_p = QtWidgets.QPushButton(self.centralwidget)
        self.add_p.setGeometry(QtCore.QRect(80, 200, 141, 28))
        self.add_p.setObjectName("add_p")
        self.delete_p = QtWidgets.QPushButton(self.centralwidget)
        self.delete_p.setGeometry(QtCore.QRect(80, 230, 141, 28))
        self.delete_p.setObjectName("delete_p")
        self.b_cal_bmi = QtWidgets.QPushButton(self.centralwidget)
        self.b_cal_bmi.setGeometry(QtCore.QRect(81, 41, 129, 25))
        self.b_cal_bmi.setObjectName("b_cal_bmi")
        self.b_password = QtWidgets.QPushButton(self.centralwidget)
        self.b_password.setGeometry(QtCore.QRect(81, 104, 129, 25))
        self.b_password.setObjectName("b_password")
        self.inv_b = QtWidgets.QPushButton(self.centralwidget)
        self.inv_b.setGeometry(QtCore.QRect(81, 136, 129, 24))
        self.inv_b.setObjectName("inv_b")
        self.list.raise_()
        self.l_tools.raise_()
        self.l_plans.raise_()
        self.add_p.raise_()
        self.delete_p.raise_()
        self.calendar.raise_()
        self.b_password.raise_()
        self.b_notes.raise_()
        self.b_cal_bmi.raise_()
        self.inv_b.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.b_notes.setText(_translate("MainWindow", "Notes"))
        self.l_tools.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#6d0036;\">Tool options</span></p></body></html>"))
        self.l_plans.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#6c0036;\">Plans for the day</span></p></body></html>"))
        self.add_p.setText(_translate("MainWindow", "+ Add"))
        self.delete_p.setText(_translate("MainWindow", "Delete"))
        self.b_cal_bmi.setText(_translate("MainWindow", "Calculation of BMI"))
        self.b_password.setText(_translate("MainWindow", "Password generating"))
        self.inv_b.setText(_translate("MainWindow", "Inventory manage"))
import c1_rc
import w1_rc
import x2_rc
